#!/bin/bash
#
# Script to disable screen blanking on the RPi
#
# You might also want to uncomment the line
# @@xscreensaver -no-splash
# in /etc/xdg/lxsession/LXDE/autostart
# and set BLANK_TIME and POWERDOWN_TIME to 0
# in /etc/kbd/config

xset dpms 0 0 0 -dpms s off s noblank s 0 0
setterm -blank 0 -powerdown 0
