#!/usr/bin/env expect

trap {
 set rows [stty rows]
 set cols [stty columns]
 stty rows $rows columns $cols < $spawn_out(slave,name)
} WINCH

spawn -noecho ssh -X jeremyj@$env(HOST)

expect password:
send $env(PASSWD)

interact
