#!/bin/bash

VERSION=`cat debian/changelog | head -n 1 | awk '{printf$2}' | awk 'sub("\\\(","")' | awk 'sub("quantal","raring")' | awk 'sub("\\\)","\n")' | head -n 1`
dch --force-distribution -D raring -v $VERSION "Raring build"
debuild -S -sa -k41F6767A
