#!/bin/bash

set -x

for search_term in "$@"
do
	search_term_plus=`echo "$search_term" | tr ' ' '+'`
	search_url=`curl -s http://www.marktplaats.nl/z.html?query="$search_term_plus" | grep "thumb-placeholder-centered juiceless-link" | awk 'BEGIN { FS = "\"" } ; { printf $6": " } ; { print $2 }'`
done
